0_arguments:
	cx\
		../src/argv.cx\
		../src/application.cx\
		0_arguments.cx ++data=../resources

1_framerate:
	cx\
		../src/argv.cx\
		../src/application.cx\
		../src/math.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		1_framerate.cx ++data=../resources

2_profiler:
	cx\
		../src/argv.cx\
		../src/application.cx\
		../src/math.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		2_profiler.cx ++data=../resources

3_window:
	cx\
		../src/argv.cx\
		../src/application.cx\
		../src/math.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		3_window.cx ++data=../resources

4_colored_quad:
	cx\
		../src/argv.cx\
		../src/application.cx\
		../src/math.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		4_colored_quad.cx ++data=../resources

5_textured_quad:
	cx\
		../src/argv.cx\
		../src/application.cx\
		../src/math.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		5_textured_quad.cx ++data=../resources

6_text:
	cx\
		../src/argv.cx\
		../src/application.cx\
		../src/math.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		6_text.cx ++data=../resources

7_menu:
	cx\
		../src/argv.cx\
		../src/application.cx\
		../src/math.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		../src/gfx/scissor.cx\
		../src/gui/layer.cx\
		../src/gui/skin.cx\
		../src/gui/batch.cx\
		../src/gui/font.cx\
		../src/gui/animation.cx\
		../src/gui/control.cx\
		../src/gui/label.cx\
		../src/gui/picture.cx\
		../src/gui/screen.cx\
		../src/gui/interface.cx\
		7_menu.cx ++data=../resources

8_button:
	cx\
		../src/argv.cx\
		../src/application.cx\
		../src/math.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		../src/gfx/scissor.cx\
		../src/gui/layer.cx\
		../src/gui/skin.cx\
		../src/gui/batch.cx\
		../src/gui/font.cx\
		../src/gui/animation.cx\
		../src/gui/control.cx\
		../src/gui/label.cx\
		../src/gui/picture.cx\
		../src/gui/screen.cx\
		../src/gui/interface.cx\
		8_button.cx ++data=../resources

9_dialog:
	cx\
		../src/argv.cx\
		../src/application.cx\
		../src/math.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		../src/gfx/scissor.cx\
		../src/gui/layer.cx\
		../src/gui/skin.cx\
		../src/gui/batch.cx\
		../src/gui/font.cx\
		../src/gui/animation.cx\
		../src/gui/control.cx\
		../src/gui/label.cx\
		../src/gui/picture.cx\
		../src/gui/screen.cx\
		../src/gui/interface.cx\
		9_dialog.cx ++data=../resources

10_custom_menu:
	cx\
		../src/argv.cx\
		../src/application.cx\
		../src/math.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		../src/gfx/scissor.cx\
		../src/gui/layer.cx\
		../src/gui/skin.cx\
		../src/gui/batch.cx\
		../src/gui/font.cx\
		../src/gui/animation.cx\
		../src/gui/control.cx\
		../src/gui/label.cx\
		../src/gui/picture.cx\
		../src/gui/screen.cx\
		../src/gui/interface.cx\
		10_custom_menu.cx ++data=../resources

11_perspective:
	cx\
		../src/argv.cx\
		../src/application.cx\
		../src/math.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		11_perspective.cx ++data=../resources


