0_arguments:
	cx\
		../src/arg/argv.cx\
		../src/app/application.cx\
		0_arguments.cx ++data=../resources

1_framerate:
	cx\
		../src/arg/argv.cx\
		../src/mat/math.cx\
		../src/app/application.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		1_framerate.cx ++data=../resources

2_profiler:
	cx\
		../src/arg/argv.cx\
		../src/mat/math.cx\
		../src/app/application.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		2_profiler.cx ++data=../resources

3_window:
	cx\
		../src/arg/argv.cx\
		../src/mat/math.cx\
		../src/app/application.cx\
		../src/app/event.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		3_window.cx ++data=../resources

4_colored_quad:
	cx\
		../src/arg/argv.cx\
		../src/mat/math.cx\
		../src/app/application.cx\
		../src/app/event.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		4_colored_quad.cx ++data=../resources

5_textured_quad:
	cx\
		../src/arg/argv.cx\
		../src/mat/math.cx\
		../src/app/application.cx\
		../src/app/event.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		5_textured_quad.cx ++data=../resources

6_text:
	cx\
		../src/arg/argv.cx\
		../src/mat/math.cx\
		../src/app/application.cx\
		../src/app/event.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		6_text.cx ++data=../resources

7_menu:
	cx\
		../src/arg/argv.cx\
		../src/mat/math.cx\
		../src/app/application.cx\
		../src/app/event.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		../src/gfx/scissor.cx\
		../src/gui/layer.cx\
		../src/gui/skin.cx\
		../src/gui/batch.cx\
		../src/gui/font.cx\
		../src/gui/animation.cx\
		../src/gui/control.cx\
		../src/gui/label.cx\
		../src/gui/picture.cx\
		../src/gui/screen.cx\
		../src/gui/interface.cx\
		7_menu.cx ++data=../resources

8_button:
	cx\
		../src/arg/argv.cx\
		../src/mat/math.cx\
		../src/app/application.cx\
		../src/app/event.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		../src/gfx/scissor.cx\
		../src/gui/layer.cx\
		../src/gui/skin.cx\
		../src/gui/batch.cx\
		../src/gui/font.cx\
		../src/gui/animation.cx\
		../src/gui/control.cx\
		../src/gui/label.cx\
		../src/gui/picture.cx\
		../src/gui/screen.cx\
		../src/gui/interface.cx\
		8_button.cx ++data=../resources

9_dialog:
	cx\
		../src/arg/argv.cx\
		../src/mat/math.cx\
		../src/app/application.cx\
		../src/app/event.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		../src/gfx/scissor.cx\
		../src/gui/layer.cx\
		../src/gui/skin.cx\
		../src/gui/batch.cx\
		../src/gui/font.cx\
		../src/gui/animation.cx\
		../src/gui/control.cx\
		../src/gui/label.cx\
		../src/gui/picture.cx\
		../src/gui/screen.cx\
		../src/gui/interface.cx\
		9_dialog.cx ++data=../resources

10_custom_menu:
	cx\
		../src/arg/argv.cx\
		../src/mat/math.cx\
		../src/app/application.cx\
		../src/app/event.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		../src/gfx/scissor.cx\
		../src/gui/layer.cx\
		../src/gui/skin.cx\
		../src/gui/batch.cx\
		../src/gui/font.cx\
		../src/gui/animation.cx\
		../src/gui/control.cx\
		../src/gui/label.cx\
		../src/gui/picture.cx\
		../src/gui/screen.cx\
		../src/gui/interface.cx\
		10_custom_menu.cx ++data=../resources

11_perspective:
	cx\
		../src/arg/argv.cx\
		../src/mat/math.cx\
		../src/app/application.cx\
		../src/app/event.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		../src/gfx/scissor.cx\
		../src/gui/layer.cx\
		../src/gui/skin.cx\
		../src/gui/batch.cx\
		../src/gui/font.cx\
		../src/gui/animation.cx\
		../src/gui/control.cx\
		../src/gui/label.cx\
		../src/gui/picture.cx\
		../src/gui/screen.cx\
		../src/gui/interface.cx\
		11_perspective.cx ++data=../resources

12_sound:
	cx\
		../src/arg/argv.cx\
		../src/mat/math.cx\
		../src/app/application.cx\
		../src/app/event.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		../src/gfx/scissor.cx\
		../src/gui/layer.cx\
		../src/gui/skin.cx\
		../src/gui/batch.cx\
		../src/gui/font.cx\
		../src/gui/animation.cx\
		../src/gui/control.cx\
		../src/gui/label.cx\
		../src/gui/picture.cx\
		../src/gui/screen.cx\
		../src/gui/interface.cx\
		../src/snd/sounds.cx\
		../src/snd/audio.cx\
		../src/snd/voice.cx\
		12_sound.cx ++data=../resources

13_camera:
	cx\
		../src/arg/argv.cx\
		../src/mat/math.cx\
		../src/app/application.cx\
		../src/app/event.cx\
		../src/fps/profiler.cx\
		../src/fps/framerate.cx\
		../src/gfx/graphics.cx\
		../src/gfx/state.cx\
		../src/gfx/effect.cx\
		../src/gfx/program.cx\
		../src/gfx/mesh.cx\
		../src/gfx/texture.cx\
		../src/gfx/target.cx\
		../src/gfx/scissor.cx\
		../src/gui/layer.cx\
		../src/gui/skin.cx\
		../src/gui/batch.cx\
		../src/gui/font.cx\
		../src/gui/animation.cx\
		../src/gui/control.cx\
		../src/gui/label.cx\
		../src/gui/picture.cx\
		../src/gui/screen.cx\
		../src/gui/interface.cx\
		../src/snd/sounds.cx\
		../src/snd/audio.cx\
		../src/snd/voice.cx\
		../src/gam/camera.cx\
		13_camera.cx ++data=../resources

